### ISSUE TITLE
In htmlmaker JSON output, also include the required toplevelheads sub-items

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template_assets#18]
We've added support for nested items within the toplevelheads JSON element. Add these to the XLS and export them accordingly.

See the final JSON here for reference: https://github.com/macmillanpublishers/htmlmaker_js/blob/master/style_config.json#L186

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted for review, https://github.com/macmillanpublishers/Word-template_assets/pull/20
