### ISSUE TITLE
Update Styles.xslm to include endnotes div, edit top-level-heads structure

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/Word-template_assets#26]

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR for this for Erica's review: https://github.com/macmillanpublishers/Word-template_assets/pull/27

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

[Matthew Retzer](https://app.asana.com/0/9492427432407/9492427432407) approved!
