### ISSUE TITLE
Add 4 styles to supported list for Bookmaker Check macro

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/Word-template_assets#8]
As per https://github.com/macmillanpublishers/bookmaker_assets/issues/50
The styles are: 
Extract - Song Lyric (extsl)
Extract - Inscription (ins)
Note Level-1 Subhead (n1)
Note Level-2 Subhead (n2)

They need to be added to Styles_Bookmaker.csv

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Erica did this :  https://github.com/macmillanpublishers/Word-template_assets/pull/10
